minterest-finance/minterest-chain-node

node/src/chain_spec.rs
pallets/controller/src/lib.rs
pallets/controller/src/mock.rs
pallets/controller/src/tests.rs
pallets/integration-tests/src/lib.rs
pallets/liquidity-pools/src/lib.rs
pallets/liquidity-pools/src/mock.rs
pallets/liquidity-pools/src/tests.rs
pallets/minterest-protocol/src/lib.rs
pallets/minterest-protocol/src/mock.rs
pallets/minterest-protocol/src/tests.rs
types.json

Renamed reserves to pools throughout the project

[BE-70] Renamed reserves to pools.

---

node/src/chain_spec.rs
pallets/controller/src/lib.rs
pallets/controller/src/mock.rs
pallets/controller/src/tests.rs
pallets/integration-tests/src/lib.rs
pallets/liquidity-pools/src/lib.rs
pallets/liquidity-pools/src/mock.rs
pallets/liquidity-pools/src/tests.rs
pallets/minterest-protocol/src/lib.rs
pallets/minterest-protocol/src/mock.rs
pallets/traits/src/lib.rs
types.json

Implemented function borrow_balance_stored in controller pallet and unit tests for it.

Al/BE-83. Function borrow_balance_stored

---

Cargo.lock
node/Cargo.toml
node/src/chain_spec.rs
node/src/command.rs
pallets/controller/src/lib.rs
pallets/controller/src/mock.rs
pallets/controller/src/tests.rs
pallets/integration-tests/src/lib.rs
pallets/minterest-protocol/src/mock.rs
runtime/src/lib.rs

Add config with new root_key.
Add command to start node using this configuration.
Add admin functions to set new InsuranceFactor && MaxBorrowRate.
Move InsuranceFactor && MaxBorrowRate to controller storage.

Ep/be 82 add admin key  and set insurancefactor maxborrowrate

---

Cargo.toml
README.md

Version upgraded and versioning info added to readme
-
**Test scenarios/Use cases:**
-

Versioning

---

pallets/controller/src/lib.rs
pallets/controller/src/mock.rs
pallets/controller/src/tests.rs
pallets/integration-tests/src/lib.rs
pallets/integration-tests/src/tests/minterest_protocol_tests.rs
pallets/minterest-protocol/src/lib.rs
pallets/minterest-protocol/src/mock.rs
pallets/minterest-protocol/src/tests.rs
primitives/src/lib.rs
runtime/src/tests.rs
service/src/chain_spec.rs
types.json

Implement transfer wrapped tokens between users;
Add Operation::Transfer;
Add transfer tests;

VP/BE-118. Transfer tokens between users.

---

README.md

Readme update
-
**Test scenarios/Use cases:**
-
The info will go to the Protocol documentation.

Version info

---

Cargo.toml
README.md

Version dump 0.6.0 -> 0.6.2 (currently developed)
No
**Test scenarios/Use cases:**
No
The info will go to the Protocol documentation.

Version dump

---

pallets/liquidation-pools/src/lib.rs
pallets/liquidation-pools/src/mock.rs
pallets/liquidation-pools/src/tests.rs
service/src/chain_spec.rs
types.json

Rebuild storage for pallet liquidation_pools.
Add new param "deviation_threshold" to LiquidationPool struct.
Add setter for this one.
Add test for setter.
Rebuild StorageMap:
previous: Liquidation_pools -> key: CurrencyId, value: struct LiquidationPool.
current:    Liquidation_pool_params -> value: struct LiquidationPoolCommonData
Liquidation_pools -> key: CurrencyId, value: struct LiquidationPool.

EP/MIN 26 Deviation threshold

---

pallets/controller/src/lib.rs
pallets/liquidity-pools/src/lib.rs
pallets/liquidity-pools/src/tests.rs

Rework accrue_interest_rate() to use calculate_interest_params() to avoid code duplication
Add getter and setter for pool data

VP/MIN-11 DRY the Accrue interest for users.

---

.github/pull_request_template.md
Makefile

API doc in template.
Make run fix.
Describe storage structure changes
**Test scenarios/Use cases:**
If applicable, describe new use cases and leave @DenisRomanovsky  mention. 
The info will go to the Protocol documentation.

[NO-TASK] Add API doc reference to commit template.

---

runtime/src/benchmarking/minterest_protocol.rs

Fixed function calls in benchmarks.
**Checklist**

[NO-TASK] Fix benchamrks

---

types.json

Fix types.json . Field 'LookupSource: AccountId' was a reason of error while exs of system pallets calling.
_No changes._
**Checklist**

[MIN-142] Fix types.json

---

.gitmodules
Cargo.lock
Cargo.toml
Makefile
pallets/controller/Cargo.toml
pallets/dex/Cargo.toml
pallets/integration-tests/Cargo.toml
pallets/liquidation-pools/Cargo.toml
pallets/liquidity-pools/Cargo.toml
pallets/minterest-model/Cargo.toml
pallets/minterest-protocol/Cargo.toml
pallets/mnt-token/Cargo.toml
pallets/prices/Cargo.toml
pallets/risk-manager/Cargo.toml
pallets/traits/Cargo.toml
rpc/Cargo.toml
runtime/Cargo.toml

- Removed ORML submodule
- Added orml-oracle crate as a dependency

[MIN-180] replace orml submodule with crate

---

types.json

Add max_ideal_balance to types.json

[NO-TASK] Add max_ideal_balance to types.json

---

types.json

Fixed types.json
**Checklist**

[NO-TASK] Add HypotheticalLiquidityData to types.json

---

README.md

AA/Updated path to benchmark test dir in README.md

AA/Updated path to benchmark test dir in README.md

---

pallets/controller/src/lib.rs
pallets/dex/src/lib.rs
pallets/integration-tests/src/lib.rs
pallets/liquidation-pools/src/lib.rs
pallets/liquidity-pools/src/lib.rs
pallets/minterest-model/src/lib.rs
pallets/minterest-protocol/src/lib.rs
pallets/risk-manager/src/lib.rs

Added missing overview for pallets.

VP/MIN-155 Pallets overview

---

pallets/integration-tests/src/lib.rs
pallets/integration-tests/src/tests/mnt_token_tests.rs

[MIN-208] Add integration test

---

pallets/controller/rpc/runtime-api/src/lib.rs
pallets/controller/rpc/src/lib.rs
pallets/controller/src/lib.rs
runtime/src/lib.rs
runtime/src/tests/mod.rs
runtime/src/tests/rpc_tests.rs

Implemented RPC to display the user's current borrow balance for a specific currency_id.
Implemented tests for it.
Added descriprion of the RPC to API documentation.
**Checklist**

AL/MIN-239. Real borrowed per asset.

---

Cargo.lock
pallets/integration-tests/src/tests/mnt_token_tests.rs
pallets/mnt-token/rpc/Cargo.toml
pallets/mnt-token/rpc/runtime-api/Cargo.toml
pallets/mnt-token/rpc/runtime-api/src/lib.rs
pallets/mnt-token/rpc/src/lib.rs
pallets/mnt-token/src/lib.rs
pallets/mnt-token/src/mock.rs
pallets/traits/src/lib.rs
rpc/Cargo.toml
rpc/src/lib.rs
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/tests/balancing_pools_tests.rs
runtime/src/tests/liquidation_tests.rs
runtime/src/tests/mod.rs
runtime/src/tests/rpc_tests.rs

Implemented RPC `get_unclaimed_mnt_balance()` for paller mnt-token. This RPC mets MNT accrued but not yet transferred to user.
Implemented tests for this RPC.
Added a description of the RPC to the API documentation.
**Checklist**

AL/MIN-253. User mnt balance.

---

service/src/chain_spec.rs

Added balances for users.
--
**Checklist**

Add balances for users.

---

scripts/docker_run.sh
scripts/init.sh

Returned directory with scripts.
-
**Checklist**

Returned directory with scripts.

---

service/src/chain_spec.rs

[NO-TASK] Add balance

---

pallets/controller/rpc/runtime-api/src/lib.rs
pallets/controller/rpc/src/lib.rs
pallets/controller/src/lib.rs
pallets/liquidity-pools/src/lib.rs
runtime/src/lib.rs
runtime/src/tests/mod.rs
runtime/src/tests/rpc_tests.rs

Add cotroller RPC to return total amount of money in the protocol
**Checklist**

VP/MIN-302. RPC protocol total value.

---

service/src/chain_spec.rs

Added initial balances.
**Checklist**

Added balances

---

pallets/liquidation-pools/src/lib.rs
pallets/liquidation-pools/src/mock.rs
pallets/liquidation-pools/src/tests.rs

Also, Fix mistake in transfer_to_liquidation_pool_should_work test
**Checklist**

AK/MIN-178. Add offchain_worker_balancing_test

---

.cargo/audit.toml
service/src/chain_spec.rs
types.json

Add balance add fix types.json

---

pallets/controller/src/lib.rs
pallets/dex/src/mock.rs
pallets/liquidation-pools/src/lib.rs
pallets/liquidity-pools/src/lib.rs
pallets/minterest-protocol/src/lib.rs
pallets/mnt-token/src/lib.rs
pallets/risk-manager/src/lib.rs
pallets/traits/src/lib.rs
runtime/src/lib.rs
runtime/src/tests/mod.rs

- Make LiquiditiPoolsManager trait inherited from PoolsManager 
- Improve calculate_exchange_rate doc
**Checklist**

[NO-TASK] Refactor PoolsManager traits

---

Cargo.lock
pallets/controller/Cargo.toml
pallets/integration-tests/Cargo.toml
pallets/liquidation-pools/Cargo.toml
pallets/liquidity-pools/Cargo.toml
pallets/minterest-model/Cargo.toml
pallets/minterest-protocol/Cargo.toml
pallets/mnt-token/Cargo.toml
pallets/risk-manager/Cargo.toml
pallets/traits/Cargo.toml
primitives/Cargo.toml
runtime/Cargo.toml

To find unused deps was used [cargo-udeps](https://github.com/est31/cargo-udeps)
**Checklist**

AK/MIN-479 Remove unused dependencies from pallets

---

pallets/controller/rpc/runtime-api/src/lib.rs
pallets/controller/rpc/src/lib.rs
runtime/src/lib.rs
runtime/src/rpc_tests.rs
types.json

Add rpc getUserData that returns values required for web 2.0 part.
Currently all values are stubbed to equal to one.
**Checklist**

MIN-480 getUserData RPC

---

primitives/src/currency.rs
types.json

Fixed issues with frontend connection after node update.
--
**Checklist**

[NO-TASK] Fix issues after updating to v.0.9.7

---

Cargo.lock
types.json

Add type Currency to types.json
**Checklist**

[NO-TASK] Fix after update to v0.9.8.

---

service/src/chain_spec.rs

[NO-TASK] Change marina public key

---

types.json

Fix types.json (change Pool -> PoolData)
**Checklist**

[NO-TASK] Fix types.json

---

pallets/risk-manager/src/lib.rs

fix setter

---

pallets/risk-manager/src/lib.rs

fix setter (#172)

---

pallets/risk-manager/src/lib.rs
pallets/risk-manager/src/tests.rs

AL/NO-TASK. Fix tests.

---

pallets/risk-manager/src/tests.rs

fix test for set_liquidation_threshold

---

pallets/risk-manager/src/lib.rs
pallets/risk-manager/src/tests.rs

AL/NO-TASK. Fix test for set_liquidation_threshold.

---

service/src/chain_spec.rs

Update initial balance for wallet.
**Checklist**

[NO-TASK] Update initial wallet balance

---

.github/workflows/ci.yml

ci cfg update
